services:
  - type: web
    name: mass-email-sender
    env: python
    buildCommand: pip install -r requirements.txt && python setup.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 